# Deploy Streamlit GPT app to Azure App Service

name: Build and deploy Python app to Azure Web App - fadiopenai

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Stable version

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      # ✅ Optional: Add tests here if needed

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'fadiopenai'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F75EDC77DA614C2FB021BDF7B051E21C }}

      # ✅ NEW: Login to Azure for CLI commands
      - name: Azure Login for CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ✅ NEW: Set Streamlit startup command
      - name: Set Streamlit startup command
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp config set \
              --resource-group fadiopen_group \
              --name fadiopenai \
              --startup-file "streamlit run app.py --server.port 8000 --server.address 0.0.0.0"
