  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'fadiopenai'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F75EDC77DA614C2FB021BDF7B051E21C }}

      - name: 'Set startup command for Streamlit'
        run: |
          az webapp config set \
            --resource-group fadiopen_group \
            --name fadiopenai \
            --startup-file "streamlit run app.py --server.port 8000 --server.address 0.0.0.0"
